### ISSUE TITLE
PDF files for schematic and board

### ISSUE THREAD

**Issue by gaudat** [neuralaxy/NeuroStimDuino#2]
For the us that do not have Eagle installed, can you upload the hardware design files in a more open format? Say PDFs, or Gerbers, or even a KiCad project?

**Comment by neuralaxy** [comment]
Hello Gaudat,

Thank you for your email and for bringing this to my attention. I have now
uploaded the gerber files on Github:
https://github.com/neuralaxy/NeuroStimDuino/tree/main/Gerbers/Gerbers_v1_1.
Please let me know if you have any issues in accessing the files.

I checked, but it seems that there is no proper way to export a KiCad
compatible project from Eagle. On one forum it was mentioned that KiCad is
able to open the board files (.brd) but not the schematic (.sch) files.
Have you tried this? I don't know how useful it will be, since I haven't
used KiCad before. Let me know if you are able to make this work. Sorry, I
wish I could be more helpful to you in this regard.

**Comment by yanwang631** [comment]
Hi, I am a graduate student researching about functional electrical stimulation control strategy, I reproduced NeuroStimDuino according to your information, but after the soldering is done, the computer does not recognize the port when I connect it via usb. We have troubleshoot some problems but still can't succeed, can you help me to analyze the reason?Can you give me a process of using the equipment？
